const questions = [
  "What’s the wildest place you’ve ever wanted to have sex?",
  "What’s your secret turn-on that you’ve never told me?",
  "Do you prefer making out or cuddling naked?",
  "Have you ever fantasized about someone else while with me?",
  "What’s your ultimate bedroom fantasy?",
  "What’s one thing you want to try in bed but are too shy to ask?",
  "How would you describe your kissing style?",
  "If you had to pick a song for our next sexy time, which would it be?",
  "What’s a secret spot on your body that feels amazing when touched?",
  "What’s the naughtiest dream you’ve had about me?",
  "What’s your favorite thing I do in bed?",
  "Have you ever wanted to try role-play with me?",
  "What’s the most adventurous place you want to make love?",
  "Have you ever sent a risky text to the wrong person?",
  "Describe your idea of a perfect date night.",
  "What’s the most embarrassing thing that’s happened to you in bed?",
  "What’s one thing you wish I did more often?",
  "What’s your favorite body part on me?",
  "If you could read my mind for one day, what would you want to know?",
  "What was your first impression of me?",
  "What’s a secret you’ve never told anyone?",
  "What’s the hottest thing I’ve ever done for you?",
  "Describe your ultimate romantic getaway with me.",
  "If you could relive any moment with me, what would it be?",
  "What’s your guilty pleasure?",
  "What’s something you find irresistible about me?",
  "What’s the silliest thing you’ve done to impress someone?",
  "What’s one thing you want to change about our relationship?",
  "What’s your most unusual turn-on?",
  "What’s your favorite pet name for me?",
];
export default questions;
